//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMICO
    {
        public int IdAcademico { get; set; }
        public int Rut { get; set; }

        public int IdCertificacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCentroAcademico { get; set; }
        public string DescripcionAcademico { get; set; }
        public string FolioRegistroAcademico { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual CENTRO_ACADEMICO CENTRO_ACADEMICO { get; set; }
        public virtual CERTIFICACION CERTIFICACION { get; set; }
        public virtual SOCIO SOCIO { get; set; }
    }
}
