//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_ACADEMICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTRO_ACADEMICO()
        {
            this.ACADEMICO = new HashSet<ACADEMICO>();
        }
    
        public int IdCentroAcademico { get; set; }
        public string NombreCentroAcademico { get; set; }
        public string EmailCentroAcademico { get; set; }
        public int TelefonoCentroAcademico { get; set; }
        public int IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMICO> ACADEMICO { get; set; }
    }
}
