//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTABLECIMIENTO_ACTUAL
    {
        public int IdEstablecimientoActual { get; set; }
        public int IdEstablecimiento { get; set; }
        public int Rut { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual ESTABLECIMIENTO ESTABLECIMIENTO { get; set; }
        public virtual SOCIO SOCIO { get; set; }
    }
}
