//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTABLECIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTABLECIMIENTO()
        {
            this.ESTABLECIMIENTO_ACTUAL = new HashSet<ESTABLECIMIENTO_ACTUAL>();
        }
    
        public int IdEstablecimiento { get; set; }
        public string NombreEstablecimiento { get; set; }
        public string IdComuna { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
        public string NombreContacto { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTABLECIMIENTO_ACTUAL> ESTABLECIMIENTO_ACTUAL { get; set; }
    }
}
