//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMAPAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMAPAGO()
        {
            this.HISTORICO_PAGO = new HashSet<HISTORICO_PAGO>();
            this.SOCIO = new HashSet<SOCIO>();
        }
    
        public int IdFormaPagoCuota { get; set; }
        public string DescripcionFormaPagoCuota { get; set; }
        public int IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_PAGO> HISTORICO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIO> SOCIO { get; set; }
    }
}
