//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_PAGO
    {
        public int IdHistoricoPago { get; set; }
        public int Rut { get; set; }
        public int IdFormaPagoCuota { get; set; }
        public System.DateTime FechaPagoCuota { get; set; }
        public string MesCancelado { get; set; }
        public int AnnoMesCancekadi { get; set; }
        public int ValorCancelado { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual FORMAPAGO FORMAPAGO { get; set; }
        public virtual SOCIO SOCIO { get; set; }
    }
}
