//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RCSTecMed_Entities : DbContext
    {
        public RCSTecMed_Entities()
            : base("name=RCSTecMed_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<ESTABLECIMIENTO> ESTABLECIMIENTO { get; set; }
        public virtual DbSet<ESTABLECIMIENTO_ACTUAL> ESTABLECIMIENTO_ACTUAL { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<FORMAPAGO> FORMAPAGO { get; set; }
        public virtual DbSet<HISTORICO_PAGO> HISTORICO_PAGO { get; set; }
        public virtual DbSet<NACIONALIDAD> NACIONALIDAD { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<REGISTRO_TECMED> REGISTRO_TECMED { get; set; }
        public virtual DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public virtual DbSet<SOCIO> SOCIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_DESK> USUARIO_DESK { get; set; }
        public virtual DbSet<USUARIO_WEB> USUARIO_WEB { get; set; }
        public virtual DbSet<ESTADO_SOCIO> ESTADO_SOCIO { get; set; }
        public virtual DbSet<ACADEMICO> ACADEMICO { get; set; }
        public virtual DbSet<CENTRO_ACADEMICO> CENTRO_ACADEMICO { get; set; }
        public virtual DbSet<CERTIFICACION> CERTIFICACION { get; set; }
    }
}
