//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_TECMED
    {
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Nacionalidad { get; set; }
        public string Institucion { get; set; }
        public System.DateTime FechaAntecedente { get; set; }
        public int Registro { get; set; }
        public string TipoInstitucion { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string NombreTitulo { get; set; }
        public string RegionTrabajo { get; set; }
        public string Mencion { get; set; }
        public string UniversidadExtranjera { get; set; }
        public string Pais { get; set; }
        public string Especialista { get; set; }
        public int IdUsuario { get; set; }
    }
}
