//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSTecMed_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIO()
        {
            this.ESTABLECIMIENTO_ACTUAL = new HashSet<ESTABLECIMIENTO_ACTUAL>();
            this.HISTORICO_PAGO = new HashSet<HISTORICO_PAGO>();
            this.ACADEMICO = new HashSet<ACADEMICO>();
        }
    
        public int Rut { get; set; }
        public string Dv { get; set; }
        public int FolioRegistro { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Domicilio { get; set; }
        public string IdComuna { get; set; }
        public string IdNacionalidad { get; set; }
        public int TelMovil { get; set; }
        public int TelFijo { get; set; }
        public string Email { get; set; }
        public int IdFormaPagoCuota { get; set; }
        public string ObservacionPagocuota { get; set; }
        public int IdUsuario { get; set; }
        public int IdEstadoSocio { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTABLECIMIENTO_ACTUAL> ESTABLECIMIENTO_ACTUAL { get; set; }
        public virtual FORMAPAGO FORMAPAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_PAGO> HISTORICO_PAGO { get; set; }
        public virtual NACIONALIDAD NACIONALIDAD { get; set; }
        public virtual ESTADO_SOCIO ESTADO_SOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMICO> ACADEMICO { get; set; }
    }
}
