-- Autor: Pedro Arrate 
-- Fecha: 01-10-2025
-- Descripción: Scripts Inicial de Creación de BD proyecto RCS-TecMed


USE [master]
GO

/****** Object:  Database [COLTECMED]    Script Date: 01-10-2025 23:04:20 ******/
CREATE DATABASE [COLTECMED]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COLTECMED', FILENAME = N'D:\Proyectos de Desarrollo\Colegio Tecnologos Medicos\DataBase\COLTECMED.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COLTECMED_log', FILENAME = N'D:\Proyectos de Desarrollo\Colegio Tecnologos Medicos\DataBase\COLTECMED_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COLTECMED].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COLTECMED] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COLTECMED] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COLTECMED] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COLTECMED] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COLTECMED] SET ARITHABORT OFF 
GO

ALTER DATABASE [COLTECMED] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COLTECMED] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COLTECMED] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COLTECMED] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COLTECMED] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COLTECMED] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COLTECMED] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COLTECMED] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COLTECMED] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COLTECMED] SET  DISABLE_BROKER 
GO

ALTER DATABASE [COLTECMED] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COLTECMED] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COLTECMED] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COLTECMED] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COLTECMED] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COLTECMED] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COLTECMED] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COLTECMED] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [COLTECMED] SET  MULTI_USER 
GO

ALTER DATABASE [COLTECMED] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COLTECMED] SET DB_CHAINING OFF 
GO

ALTER DATABASE [COLTECMED] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [COLTECMED] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [COLTECMED] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [COLTECMED] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [COLTECMED] SET QUERY_STORE = OFF
GO

ALTER DATABASE [COLTECMED] SET  READ_WRITE 
GO


